backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "events"
    label: "Events"
    folder: "static/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: string}
  - name: "projects"
    label: "Projects"
    folder: "static/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date", name: "start-date", widget: "datetime"}
      - {label: "End Date", name: "end-date", widget: "datetime"}
      - {label: "Image", name: "image", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "goals"
    label: "General Goals"
    folder: "static/goals"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Goal", name: "goal", widget: "string"}
  - name: "objectives"
    label: "Year Objectives"
    folder: "static/objectives"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Objective", name: "objective", widget: "string"}
  - name: "members"
    label: "Members"
    folder: "static/members"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Member", name: "member", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
