backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "events"
    label: "Events"
    folder: "static/events"
    extension: "json"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: string}
  - name: "projects"
    label: "Projects"
    folder: "static/projects"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "goals"
    label: "General Goals"
    folder: "static/goals"
    extension: "json"
    create: true
    fields:
      - {label: "ID", name: "title", widget: "string"}
      - {label: "Goal", name: "goal", widget: "string"}
  - name: "objectives"
    label: "Year Objectives"
    folder: "static/objectives"
    extension: "json"
    create: true
    fields:
      - {label: "ID", name: "title", widget: "string"}
      - {label: "Objective", name: "objective", widget: "string"}
  - name: "members"
    label: "Members"
    folder: "static/members"
    extension: "json"
    create: true
    fields:
      - {label: "Member", name: "title", widget: "string"}
      - {label: "Occupation", name: "occupation", widget: "string"}
  - name: "contacts"
    label: "Contact (Only one Entry)"
    folder: "static/contact"
    extension: "json"
    create: true
    fields:
      - {label: "ID", name: "title", widget: "string"}
      - {label: "Contact URL", name: "contact", widget: "string"}
